# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - 3000:3000
      - 9229:9229 # used for debugging on VS code
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todos
    ports:
      - 5431:5432
